"""Base-game vs DLC classification for a game's goal squares.

`<data_dir>/squares/base_game.json` and `<data_dir>/squares/dlc.json` (see
pipeline.consolidate, storage.json_export.write_squares/read_squares) are the
consolidated reference of every goal square text seen across previously extracted
matches, tagged with the game type it belongs to -- there's no programmatic way to know
this otherwise, so the reference only knows what previously extracted matches have
resolved (whether by the overlay's own subtitle or a user's prompted answer, see
extract.py) and rolled into it via `square consolidate`. This used to be a single,
hand-maintained `<data_dir>/squares/squares.json` file; it was replaced (issue #75) once
`pipeline.consolidate` started deriving the same text->game_type knowledge automatically
from match history, making a separately hand-maintained file redundant. Unlike
squares.json, base_game.json/dlc.json are wholly regenerated by `square consolidate` from
local match history and gitignored rather than committed -- until that's been run against
a data directory (a fresh checkout, or one that's never extracted anything), every game
fails to infer here, the same "ships empty" tolerance squares.json used to have. This is
only extract_video's fallback, though -- game_type_label.py reads the overlay's own "BASE
GAME"/"DLC" subtitle directly and normally succeeds first, so in practice this reference
(and, failing both, prompting the user) only covers whatever the direct read misses (see
extract.py and cli/app.py).
"""

import logging
from collections import Counter
from pathlib import Path

from scadustats.models import GameType
from scadustats.storage.json_export import read_squares

logger = logging.getLogger(__name__)


def load_known_squares(squares_dir: str | Path) -> dict[str, GameType]:
    """Every square text known so far, across both game types, flattened from
    squares_dir/base_game.json and squares_dir/dlc.json (see
    storage.json_export.read_squares) into the single text->GameType map
    infer_game_type below expects. Either file missing contributes nothing for that game
    type -- read_squares already treats that as an empty list, not an error."""
    known: dict[str, GameType] = {}
    for game_type, squares in read_squares(squares_dir).items():
        for square in squares:
            known[square.text] = game_type
    return known


def infer_game_type(
    square_texts: list[list[str]], known_squares: dict[str, GameType]
) -> GameType | None:
    """None if none of the board's 25 squares are in known_squares (including when
    known_squares is empty) -- there's nothing to infer from. If the matched squares
    disagree (which shouldn't happen: a board's squares are drawn from one pool, not
    mixed), the majority wins and a warning is logged, rather than failing outright."""
    matched = [
        known_squares[text] for row in square_texts for text in row if text in known_squares
    ]
    if not matched:
        return None

    counts = Counter(matched)
    if len(counts) > 1:
        logger.warning("board has squares from more than one game type: %s", dict(counts))
    return counts.most_common(1)[0][0]
