"""Human-reviewable YAML export of one player's dynamically computed stats (see
pipeline.consolidate.consolidate_players), as `stats.yaml` under each player's own
`<data_dir>/players/<slug>/` directory -- wholly regenerated by `player consolidate` on
every run, and gitignored (see the `data/players/*/*` rule in .gitignore) since it's
disposable output, not hand-authored content.

This is the dynamic half of a player's profile split by issue #82: the hand-curated
identity half (id/twitch/avatar/bio) is storage.player_info's `info.yaml`, written into
the very same `<slug>/` directory but carved back out of .gitignore since it's meant to
be committed -- this module carries no fields for it and never touches it.
"""

from pathlib import Path

import yaml

from scadustats.models import PlayerStats


def player_stats_path(players_dir: str | Path, slug: str) -> Path:
    """The path write_player_stats writes (or would write) one player's stats to --
    `<players_dir>/<slug>/stats.yaml`."""
    return Path(players_dir) / slug / "stats.yaml"


def _stats_to_dict(stats: PlayerStats) -> dict:
    """model_dump(mode="json") already gives every field in models.PlayerStats's own
    declaration order (matching the sort_keys=False below) with game_type_records' GameType
    keys turned into their plain string value -- season_records is the one thing still
    worth a manual pass, sorted by season here rather than left in whatever order it was
    built in, for a stable, diffable file.
    """
    dumped = stats.model_dump(mode="json")
    dumped["season_records"] = dict(sorted(dumped["season_records"].items()))
    return dumped


def write_player_stats(players_dir: str | Path, stats: PlayerStats) -> Path:
    """Write one player's stats to `<players_dir>/<slug>/stats.yaml` (see
    player_stats_path), creating that player's directory if it doesn't exist yet.
    Unconditionally overwrites -- every field here is wholly regenerated by this run's
    consolidate_players output, with nothing hand-owned to protect (unlike
    storage.player_info.write_player_info).

    Field order in the written file follows models.PlayerStats's own declaration order
    (sort_keys=False) rather than alphabetical, so a contributor reading the file top to
    bottom sees identity, then derived stats -- not an arbitrary re-sort of them.
    """
    path = player_stats_path(players_dir, stats.slug)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(_stats_to_dict(stats), sort_keys=False, allow_unicode=True)
    path.write_text(body)
    return path


def read_player_stats(path: str | Path) -> PlayerStats:
    """Inverse of write_player_stats: parses one player's YAML stats file back into the
    PlayerStats it was serialized from.

    Every field but slug/display_name is optional here -- a file written before it existed
    (season_records/game_record/game_type_records/all_matches/top_squares_base_game/
    top_squares_dlc all postdate the very first version of this file) reads back as that
    field's own empty default rather than a KeyError, and a legacy plain-text top_squares
    entry is normalized to a zero mark count -- see PlayerStats's own validation.
    """
    data = yaml.safe_load(Path(path).read_text())
    return PlayerStats.model_validate(data)


def read_players_stats(players_dir: str | Path) -> dict[str, PlayerStats]:
    """Every player's `stats.yaml` already on disk under players_dir, keyed by its
    parent directory's name (the slug) -- empty if players_dir doesn't exist yet (a
    fresh checkout, or one `player consolidate` has never run against), the same
    "ships empty" tolerance pipeline.squares/read_squares has for a data directory with
    no squares reference yet.
    """
    directory = Path(players_dir)
    if not directory.is_dir():
        return {}
    return {
        path.parent.name: read_player_stats(path) for path in sorted(directory.glob("*/stats.yaml"))
    }
