"""Human-reviewable YAML export of one player's dynamically computed stats (see
pipeline.consolidate.consolidate_players), as `stats.yaml` under each player's own
`<data_dir>/players/<slug>/` directory -- wholly regenerated by `player consolidate` on
every run, and gitignored (see the `data/players/*/*` rule in .gitignore) since it's
disposable output, not hand-authored content.

This is the dynamic half of a player's profile split by issue #82: the hand-curated
identity half (id/twitch/avatar/bio) is storage.player_info's `info.yaml`, written into
the very same `<slug>/` directory but carved back out of .gitignore since it's meant to
be committed -- this module carries no fields for it and never touches it.
"""

from pathlib import Path

import yaml

from scadustats.models import GameType, MatchRecord, PlayerStats, SquareMarks, WinLoss


def player_stats_path(players_dir: str | Path, slug: str) -> Path:
    """The path write_player_stats writes (or would write) one player's stats to --
    `<players_dir>/<slug>/stats.yaml`."""
    return Path(players_dir) / slug / "stats.yaml"


def _stats_to_dict(stats: PlayerStats) -> dict:
    return {
        "slug": stats.slug,
        "display_name": stats.display_name,
        "season_records": {
            season: {"wins": record.wins, "losses": record.losses, "draws": record.draws}
            for season, record in sorted(stats.season_records.items())
        },
        "game_record": {"wins": stats.game_record.wins, "losses": stats.game_record.losses},
        "game_type_records": {
            game_type.value: {"wins": record.wins, "losses": record.losses}
            for game_type, record in stats.game_type_records.items()
        },
        "all_matches": stats.all_matches,
        "top_squares_base_game": [
            {"text": square.text, "marks": square.marks} for square in stats.top_squares_base_game
        ],
        "top_squares_dlc": [
            {"text": square.text, "marks": square.marks} for square in stats.top_squares_dlc
        ],
    }


def write_player_stats(players_dir: str | Path, stats: PlayerStats) -> Path:
    """Write one player's stats to `<players_dir>/<slug>/stats.yaml` (see
    player_stats_path), creating that player's directory if it doesn't exist yet.
    Unconditionally overwrites -- every field here is wholly regenerated by this run's
    consolidate_players output, with nothing hand-owned to protect (unlike
    storage.player_info.write_player_info).

    Field order in the written file follows models.PlayerStats's own declaration order
    (sort_keys=False) rather than alphabetical, so a contributor reading the file top to
    bottom sees identity, then derived stats -- not an arbitrary re-sort of them.
    """
    path = player_stats_path(players_dir, stats.slug)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(_stats_to_dict(stats), sort_keys=False, allow_unicode=True)
    path.write_text(body)
    return path


def _dict_to_square_marks(entry: dict | str) -> SquareMarks:
    """One top_squares_base_game/top_squares_dlc entry -- a plain text string, for a file
    written before mark counts were recorded here, reads back as an unknown (zero) count
    rather than failing to parse; every field consolidate_players fills in here is
    wholly regenerated on the next `player consolidate` run anyway (see PlayerStats),
    so a stale mark count surviving even one extra run costs nothing."""
    if isinstance(entry, str):
        return SquareMarks(text=entry, marks=0)
    return SquareMarks(**entry)


def _dict_to_stats(data: dict) -> PlayerStats:
    return PlayerStats(
        slug=data["slug"],
        display_name=data["display_name"],
        season_records={
            season: MatchRecord(**record)
            for season, record in data.get("season_records", {}).items()
        },
        game_record=WinLoss(**data["game_record"]) if data.get("game_record") else WinLoss(),
        game_type_records={
            GameType(game_type): WinLoss(**record)
            for game_type, record in data.get("game_type_records", {}).items()
        },
        all_matches=data.get("all_matches", []),
        top_squares_base_game=[
            _dict_to_square_marks(square) for square in data.get("top_squares_base_game", [])
        ],
        top_squares_dlc=[
            _dict_to_square_marks(square) for square in data.get("top_squares_dlc", [])
        ],
    )


def read_player_stats(path: str | Path) -> PlayerStats:
    """Inverse of write_player_stats: parses one player's YAML stats file back into the
    PlayerStats it was serialized from."""
    data = yaml.safe_load(Path(path).read_text())
    return _dict_to_stats(data)


def read_players_stats(players_dir: str | Path) -> dict[str, PlayerStats]:
    """Every player's `stats.yaml` already on disk under players_dir, keyed by its
    parent directory's name (the slug) -- empty if players_dir doesn't exist yet (a
    fresh checkout, or one `player consolidate` has never run against), the same
    "ships empty" tolerance pipeline.squares/read_squares has for a data directory with
    no squares reference yet.
    """
    directory = Path(players_dir)
    if not directory.is_dir():
        return {}
    return {
        path.parent.name: read_player_stats(path) for path in sorted(directory.glob("*/stats.yaml"))
    }
