"""Human-reviewable YAML export of one goal square's dynamically computed stats (see
pipeline.consolidate.consolidate_square_stats), as `<data_dir>/square_stats/<game_type>/
<id>.yaml` -- wholly regenerated by `square stats` on every run, and gitignored along with
the rest of `data/` since it's disposable output.

Kept out of `<data_dir>/squares/` on purpose: that directory is the consolidated reference
(storage.json_export.write_squares), and a consumer that walks it wholesale -- the
scadustats-site's square index reads every file under its `data/squares/` as a list of
reference squares -- would mistake a stats file for one. One subdirectory per game type,
since a square's id is only unique within its own game type (see
pipeline.consolidate._unique_id).
"""

from pathlib import Path

import yaml

from scadustats.models import GameType, SquareStats


def square_stats_path(square_stats_dir: str | Path, game_type: GameType, square_id: str) -> Path:
    """The path write_square_stats writes (or would write) one square's stats to --
    `<square_stats_dir>/<game_type>/<id>.yaml`."""
    return Path(square_stats_dir) / game_type.value / f"{square_id}.yaml"


def write_square_stats(square_stats_dir: str | Path, stats: SquareStats) -> Path:
    """Write one square's stats (see square_stats_path), creating its game type's
    directory if it doesn't exist yet. Unconditionally overwrites, like
    storage.player_stats.write_player_stats -- every field is regenerated each run.

    Field order follows models.SquareStats's own declaration order (sort_keys=False).
    """
    path = square_stats_path(square_stats_dir, stats.game_type, stats.id)
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(stats.model_dump(mode="json"), sort_keys=False, allow_unicode=True)
    path.write_text(body)
    return path


def read_square_stats(path: str | Path) -> SquareStats:
    """Inverse of write_square_stats."""
    return SquareStats.model_validate(yaml.safe_load(Path(path).read_text()))
